/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.ethaden.java.vulnerable.ciper.suite;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Properties;

class AppTest {
    @Test void appHasAGreeting() {
        Properties properties = new Properties();
        App classUnderTest = new App(properties);
        // Do nothing
    }
}
